discord:
  webhook_url_file: ".secrets/DWU"

app:
  headless: false

camera:
  width: 320
  height: 240
  # width: 1920
  # height: 1080
  fps: 2

detection:
  duration_threshold: 3.0
  reset_threshold: 1.0
  confidence: 0.4
  class_id: 15
  use_motion_filter: true
  motion_threshold: 500
  debug_motion: false
