[project]
name = "cat-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=4.12.0.88",
    "optuna>=4.5.0",
    "ultralytics>=8.3.246",
    "PyYAML",
    "requests",
    "pylint>=4.0.5",
    "tensorflow>=2.21.0",
    "mnn>=3.4.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.11",
]

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors (PEP8準拠チェック)
    "W",  # pycodestyle warnings
    "F",  # Pyflakes (未使用変数などの論理エラー)
    "I",  # isort (importの並び順)
    "B",  # flake8-bugbear (バグの可能性が高い書き方)
]
ignore = [
    "E501", # 行の長さ違反 (フォーマッターに任せるため無視推奨)
]

[tool.ruff.format]
quote-style = "double"
